##############################
# Monitors
##############################

monitor=,preferred,auto,1

##############################
# Variables
##############################

$mod = SUPER
$terminal = kitty
$menu = wofi --show drun

##############################
# Programs
##############################

exec-once = waybar
exec-once = nm-applet --indicator

##############################
# General
##############################

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(444444aa)

    resize_on_border = true
}

##############################
# Decoration
##############################

decoration {
    rounding = 8

    blur {
        enabled = false
    }
}

##############################
# Animations
##############################

animations {
    enabled = yes
}

##############################
# Input
##############################

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }
}

##############################
# Layout
##############################

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}

##############################
# Keybindings
##############################


bind = SUPER, B, exec, firefox

bind = $mod, Return, exec, $terminal
bind = $mod, D, exec, $menu

bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod SHIFT, Space, togglefloating

# Vim navigation
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

# Move windows
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# Resize windows
bind = $mod CTRL, H, resizeactive, -50 0
bind = $mod CTRL, L, resizeactive, 50 0
bind = $mod CTRL, K, resizeactive, 0 -50
bind = $mod CTRL, J, resizeactive, 0 50

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

##############################
# Mouse
##############################

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
