wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpaper/wet, street photography, lights, street, umbrella, urban.jpeg
    fit_mode = cover
}


wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/wet, street photography, lights, street, umbrella, urban.jpeg
    fit_mode = cover
}
